.TH "iw_auth_descr" 3 "Thu Mar 22 2018" "Version 0.0.1" "ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iw_auth_descr
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "const char * \fBlabel\fP"
.br
.ti -1c
.RI "const struct \fBiwmask_name\fP * \fBnames\fP"
.br
.ti -1c
.RI "const int \fBnum_names\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file iwlist\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ragnarok from the source code\&.
