.TH "iw_auth_descr" 3 "Wed Mar 28 2018" "Version 0.0.1" "Ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iw_auth_descr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "const char * \fBlabel\fP"
.br
.ti -1c
.RI "const struct \fBiwmask_name\fP * \fBnames\fP"
.br
.ti -1c
.RI "const int \fBnum_names\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ragnarok from the source code\&.
