.TH "Y:/Documents/ragnarok/src/client/iwlist.c" 3 "Thu Mar 22 2018" "Version 0.0.1" "ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y:/Documents/ragnarok/src/client/iwlist.c \- Modified file from HP wireless-tools's - \fBiwlist\&.c\fP\&. I modified stuff to get it working with ragnarok and ragnarok-srv with our own functions\&. Initial header is at the top of the file behind the Doxygen header with the same license\&. Doc is directly in the file for the moment\&. Without this lib we could't get this project done\&. You guys rock ! Thank you so much\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br
\fC#include <iwlib\&.h>\fP
.br
\fC#include <include/client_tool\&.h>\fP
.br
\fC#include <include/client\&.h>\fP
.br
\fC#include <include/common\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBiwscan_state\fP"
.br
.ti -1c
.RI "struct \fBiwmask_name\fP"
.br
.ti -1c
.RI "struct \fBiw_auth_descr\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIW_SCAN_HACK\fP   0x8000"
.br
.ti -1c
.RI "#define \fBIW_EXTKEY_SIZE\fP   (sizeof(struct iw_encode_ext) + IW_ENCODING_TOKEN_MAX)"
.br
.ti -1c
.RI "#define \fBIW_ARRAY_LEN\fP(x)   (sizeof(x)/sizeof((x)[0]))"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_WEP40\fP   1"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_TKIP\fP   2"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_WRAP\fP   3"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_CCMP\fP   4"
.br
.ti -1c
.RI "#define \fBIW_IE_CIPHER_WEP104\fP   5"
.br
.ti -1c
.RI "#define \fBIW_IE_KEY_MGMT_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBIW_IE_KEY_MGMT_802_1X\fP   1"
.br
.ti -1c
.RI "#define \fBIW_IE_KEY_MGMT_PSK\fP   2"
.br
.ti -1c
.RI "#define \fBIW_IE_KEY_MGMT_NUM\fP   IW_ARRAY_LEN(iw_ie_key_mgmt_name)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBiwscan_state\fP \fBiwscan_state\fP"
.br
.ti -1c
.RI "typedef struct \fBiwmask_name\fP \fBiwmask_name\fP"
.br
.ti -1c
.RI "typedef struct \fBiw_auth_descr\fP \fBiw_auth_descr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBiw_print_ie_wpa\fP (unsigned char *iebuf, int buflen)"
.br
.ti -1c
.RI "static void \fBiw_print_gen_ie\fP (unsigned char *buffer, int buflen)"
.br
.ti -1c
.RI "static void \fBprint_scanning_token\fP (struct stream_descr *stream, struct iw_event *event, struct \fBiwscan_state\fP *state, struct iw_range *iw_range, int has_range)"
.br
.ti -1c
.RI "static int \fBprint_scanning_info\fP (int skfd, char *ifname, char *args[], int count)"
.br
.ti -1c
.RI "int \fBrun_iwlist\fP (char const *interface)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Modified file from HP wireless-tools's - \fBiwlist\&.c\fP\&. I modified stuff to get it working with ragnarok and ragnarok-srv with our own functions\&. Initial header is at the top of the file behind the Doxygen header with the same license\&. Doc is directly in the file for the moment\&. Without this lib we could't get this project done\&. You guys rock ! Thank you so much\&. 


.PP
\fBAuthor:\fP
.RS 4
Mathieu Hautebas 
.RE
.PP
\fBDate:\fP
.RS 4
22 March 2018 
.RE
.PP
\fBSee also:\fP
.RS 4
https://hewlettpackard.github.io/wireless-tools/Tools.html 
.PP
https://github.com/HewlettPackard/wireless-tools 
.RE
.PP

.PP
Definition in file \fBiwlist\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ragnarok from the source code\&.
