.TH "iwmask_name" 3 "Wed Mar 28 2018" "Version 0.0.1" "Ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iwmask_name \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBmask\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ragnarok from the source code\&.
