.TH "iwscan_state" 3 "Thu Mar 22 2018" "Version 0.0.1" "ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iwscan_state
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBap_num\fP"
.br
.ti -1c
.RI "int \fBval_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file iwlist\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ragnarok from the source code\&.
