.TH "src/server/server.c" 3 "Wed Mar 28 2018" "Version 0.0.1" "Ragnarok" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/server.c \- file containing functions for the server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <include/server\&.h>\fP
.br
\fC#include <include/common\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBINThandler\fP (int sig)"
.br
.RI "\fICatch ctrl+c to close sock and exit correctly Since it's a deamon this function is useless\&. I keep it for the moment\&. \fP"
.ti -1c
.RI "int \fBinit_srv_daemon\fP (void)"
.br
.RI "\fIinit deamon for the server First we check if the pidfile exists\&. If it exists, it means client is already running\&. Print pid of process the quit\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBsock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
file containing functions for the server\&. 


.PP
\fBAuthor:\fP
.RS 4
Mathieu Hautebas 
.RE
.PP
\fBDate:\fP
.RS 4
22 March 2018 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int init_srv_daemon (void)"

.PP
init deamon for the server First we check if the pidfile exists\&. If it exists, it means client is already running\&. Print pid of process the quit\&. 
.PP
.nf
1 if (file_exists(pidfile))
2 {
3     fp = fopen(pidfile, "r");
4     fprintf(stdout, "[-] ragnarok is already running\n");
5     getline(&pid_val, &len, fp);
6     fprintf(stdout, "[i] PID = %s\r", pid_val);
7     fclose(fp);
8     exit(-1);
9 }

.fi
.PP
 We create a normal process and a child process\&. We kill parent process and set a new session\&. Close stdin, stdout and stderr for ragnarok 
.PP
.nf
1 close(STDIN_FILENO);
2 close(STDOUT_FILENO);
3 close(STDERR_FILENO);

.fi
.PP
 
.PP
\fBReturns:\fP
.RS 4
returns 0 if everything's done well or a number != 0 if any issue or just exit()\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
https://www.thegeekstuff.com/2012/02/c-daemon-process/ 
.RE
.PP

.SS "void INThandler (int sig)"

.PP
Catch ctrl+c to close sock and exit correctly Since it's a deamon this function is useless\&. I keep it for the moment\&. 
.PP
\fBReturns:\fP
.RS 4
void, no return just exit() the program 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Ragnarok from the source code\&.
